[package]
authors = ["Yao Noel Achi <achi.noel@hotmail.com>"]
categories = ["data-structures", "filesystem"]
name = "ybitcast"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing = "0"
crc32fast = "1"

[dev-dependencies]
tempfile = "3.20.0"

